<?php

namespace App;

use Symfony\Bundle\FrameworkBundle\Kernel\MicroKernelTrait;
use Symfony\Component\HttpKernel\Kernel as BaseKernel;

class Kernel extends BaseKernel
{
    use MicroKernelTrait;

    public function boot(): void
    {
        parent::boot(); // TODO: Change the autogenerated stub

        date_default_timezone_set($this->getContainer()->getParameter('timezone') ?? 'UTC');
    }
}
