name: Test
on:
  workflow_call:
    inputs:
      UNIT_TEST_THRESHOLD:
        required: true
        type: string
    secrets:
      GIT_TOKEN:
        required: true

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set .env variables
        run: |
          cp .env.example .env

      - name: Update auth.json
        run: |
          cat > auth.temp.json << EOF
            {
              "github-oauth": {
                "github.com": "${{ secrets.GIT_TOKEN }}"
              }
            }
          EOF
          jq . auth.temp.json > auth.json
          rm auth.temp.json

      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' 
      
      - name: Install Python dependencies
        run: |
          pip install bs4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"

      - name: Install php dependencies
        uses: php-actions/composer@v6
        with:
          php_version: 8.2
          php_extensions: gd intl bcmath curl xml zip mbstring mysqli iconv pdo_mysql
          version: 2.x

      - name: Run php mess detector
        run: composer run-script phpmd

      - name: Run php code sniffer
        run: composer run-script phpcs

      - name: Run php static analysis
        run: composer run-script phpstan
        continue-on-error: true

      - name: Run php unit test
        run: |
          XDEBUG_MODE=coverage php bin/phpunit --coverage-html target/coverage --log-junit target/coverage/junit_report.xml
        continue-on-error: true

      - name: Create unitest report
        if: success() || failure() 
        id: unitest-report
        run: |
          unitest_report=$(python .github/scripts/unitest-report.py target/coverage/junit_report.xml target/coverage/junit_report_convert.txt)
          echo "#### Unit Test Report" >> target/coverage/unitest_summary.md
          echo "$unitest_report" >> target/coverage/unitest_summary.md
          echo "---" >> target/coverage/unitest_summary.md

      - name: Archive code coverage results
        id: artifact-upload-step
        if: success() || failure() 
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: target
          retention-days: 3
   
      - name: Check code coverage
        id: check-code-coverage
        if: success() || failure() 
        run: |
          ratio=$(python .github/scripts/unitest-threshold.py target/coverage/index.html)
          comparison=$(echo "$ratio > ${{ inputs.UNIT_TEST_THRESHOLD }}" | bc -l)
          echo "Current coverage: $ratio%"
          echo "Coverage threshold: ${{ inputs.UNIT_TEST_THRESHOLD }}%"
          echo "TEST_COVERAGE=$ratio" >> "$GITHUB_OUTPUT"
          if [ "$comparison" -eq 1  ]; then
            COVERAGE_STATUS=PASSED
            echo "COVERAGE_STATUS=$COVERAGE_STATUS" >> "$GITHUB_OUTPUT"
          else
            COVERAGE_STATUS=FAILED
            echo "COVERAGE_STATUS=$COVERAGE_STATUS" >> "$GITHUB_OUTPUT"
          fi

          coverage_report="#### Coverage Report 
          - Current coverage: $ratio% \\
          Coverage threshold: ${{ inputs.UNIT_TEST_THRESHOLD }}% \\
          Check coverage condition: **$COVERAGE_STATUS**
          > **_Detail test report:_**  ${{ steps.artifact-upload-step.outputs.artifact-url }}"
          echo "$coverage_report" >> target/coverage/unitest_summary.md
          cat target/coverage/unitest_summary.md >> $GITHUB_STEP_SUMMARY
      
      - uses: mshick/add-pr-comment@v2
        name: Add comment to Pull Request
        if: github.event_name == 'pull_request'|| github.event_name == 'issue_comment'
        with:
          message-path: target/coverage/unitest_summary.md
